### ISSUE TITLE
Marketplace Broken on Safari 18

### ISSUE THREAD

**Issue by craigrobben** [GSA/marketplace-fedramp-gov#108]
It appears that once again that no companies/products show up in the Marketplace when using the latest version of Safari, v18 on either iOS or macOS.  Not sure what Apple did this time to break it, but sure would be nice if it worked in Safari.

The first image is Safari 18.01 under macOS 14.7, the second is Chrome 129.0.6668.101 (arm64) on the same system.
<img width="1269" alt="Screenshot 2024-10-17 at 3 51 37 PM" src="https://github.com/user-attachments/assets/8168c14c-fa66-4cde-94d7-2bb237b3be0e">
<img width="985" alt="Screenshot 2024-10-17 at 3 52 19 PM" src="https://github.com/user-attachments/assets/fee91136-7217-41c0-8ec8-52d5f961729b">

**Comment by rhoesing** [comment]
@shivaalipour Can you have the devs take a look at this?

**Comment by shivaalipour** [comment]
thanks [craigrobben](https://github.com/craigrobben). The issue has been resolved. Please let us know if you encounter any further issues with the Marketplace. 

commit 586f6f78258fdd88d0dbd7525fe7542dd63a3fef

**Comment by craigrobben** [comment]
Confirmed.  Thanks all!
