### ISSUE TITLE
Process to request additional categories for the FedRAMP Marketplace?

### ISSUE THREAD

**Issue by richbrown6** [GSA/marketplace-fedramp-gov#14]
Is there a defined process on how to request new categories for the Marketplace?

Can we please add “Contact Center as a Service (CCaaS)” and/or “Contact Center” as new category options?

**Comment by richbrown6** [comment]
Good morning Ryan,
FedRAMP ID is FR2131766015 - let's go with:
- Collaboration
- Communication
- Contact Center
- Customer Relations Management (CRM)
- Customer Service

**Comment by rhoesing** [comment]
Hi Rich,

I updated your Business Categories: https://marketplace.fedramp.gov/products/FR2131766015

Do you have a Sales email and or a UEI number you would like us to add? Still waiting on an updated PNG file logo via email.

**Comment by rhoesing** [comment]
Fixed.

**Comment by richbrown6** [comment]
Good morning Ryan,

Updates for the following items:

  *   UEI: DD9KMGMUZM47
  *   Sales E-Mail: ***@***.******@***.***>

Thanks for your help!

Regards,
Rich

Rich Brown
Principal Product Manager
W 703.673.1679
M 703.966.2446
***@***.******@***.***>

***@***.***<http://www.genesys.com/>
***@***.******@***.******@***.******@***.******@***.******@***.***<http://blog.genesys.com/>
