### ISSUE TITLE
Many CSP logos are missing

### ISSUE THREAD

**Issue by richbrown6** [GSA/marketplace-fedramp-gov#15]
What's the process to request that CSP logo issues be corrected?

It appears that a number are missing from this folder: https://www.fedramp.gov/assets/img/logos/CSP_logos/

**Comment by rhoesing** [comment]
Rich,

Somewhere in our migration we lost a few logos that we will need to reach out to vendors to get.  Feel free to sending your information to ryan.hoesing@gsa.gov and I can get your information updated.

**Comment by rhoesing** [comment]
Logos have been fixed.
