### ISSUE TITLE
Rendering of a Marketplace product page via Edge displays all the informational text when browsing

### ISSUE THREAD

**Issue by richbrown6** [GSA/marketplace-fedramp-gov#16]
Found this by accident.
<img width="956" alt="Product page via Ege" src="https://github.com/GSA/marketplace-fedramp-gov/assets/137185480/9f7fb764-206f-483f-93be-0ca157d6ae1c">

**Comment by rhoesing** [comment]
Hi Rich,

Can you provide more detail on why that showed or how you found by accident?

**Comment by richbrown6** [comment]
It appears to have been a fluke, as I cannot reproduce when re-launching in Edge.
