### ISSUE TITLE
Marketplace via mobile browser doesn't support searching?

### ISSUE THREAD

**Issue by richbrown6** [GSA/marketplace-fedramp-gov#17]
Accessed the Marketplace via a mobile browser (Chrome), and while there is the ability to filter by Products, Agencies or Assessors, there is no way to search.

**Comment by echovanderhyden** [comment]
@michaelfrising - i added the search functionality to mobile break of /products /agencies /assessors. can you beautify it?

**Comment by shivaalipour** [comment]
@shivaalipour to update design

**Comment by shivaalipour** [comment]
issue resolved
