### ISSUE TITLE
Information Not Loading in Firefox and Safari

### ISSUE THREAD

**Issue by Kalkn83** [GSA/marketplace-fedramp-gov#18]
When navigating to Qualys's Moderate page on FedRAMP Marketplace (https://marketplace.fedramp.gov/products/F1508207205) using Firefox and Safari (both in normal mode and private mode), a lot of information never loads as seen in attached screenshot. Using Chrome, information loads without problems. 
![image001](https://github.com/GSA/marketplace-fedramp-gov/assets/119264471/990f3249-b9cc-4ba6-b1ea-d43288d8b0fa)

**Comment by shivaalipour** [comment]
@shivaalipour push the correct branch to main branch

**Comment by shivaalipour** [comment]
@echovanderhyden, I see you made the edits on July 11th on the demo branch. I pushed the commits to the main branch on July 20th but I am still having issues with Safari displaying the correctly. Can you help me figure out why?
