### ISSUE TITLE
Website Marketplace Search

### ISSUE THREAD

**Issue by GitGonzo77** [GSA/marketplace-fedramp-gov#20]
Please reenable the ability to search the Marketplace for “Service Description”. The filter/search is no longer useful. If i need to find a vendor that provides, space reservation/hoteling as an example i have to know the company name which is not practical.

**Comment by fac-trax** [comment]
I would like to second GitGonzo77's motion. And would go further on severity: FedRAMP Marketplace is broken in the Edge and Firefox browsers for all DHS users. Typing in a word and pressing enter does absolutely nothing. Please fix.

Initially, we were told this was a Let's Encrypt CA problem. It is not. HSEN does NOT block certs on outbound traffic. Also, a server responding with a 404 is not a DHS issue. The error is : Failed to load resource: the server responded with a status of 404 () at cv (main.36a5a67128e91e98.js:1:50786).

**Comment by shivaalipour** [comment]
@GitGonzo77 thank you for the feedback. We have added "service descriptions" to the search parameters. You should be able to search keywords that are in the CSO's service description now, hopefully making the experience on the FedRAMP Marketplace easier for you. Please let us know if you have any further suggestions. 

8/24 changes pushed to main site
