### ISSUE TITLE
The Marketplace has different dates for East Coast and West Coast

### ISSUE THREAD

**Issue by DrSCarter** [GSA/marketplace-fedramp-gov#21]
Sir/Ma’am,

The authorization dates to the cloud services’ authorizations dates show different for those that live on the East Coast versus those that live on the West Coast.  This is several offerings but just to give an example for 2 of them:

AWS East/West shows 5/2/2013 for us on the East Coast, it shows 4/30 for those on the West Coast.
Azure Government shows 5/3/2019 for us on the East Coast, it shows 5/2 for those on the West Coast.

This has been a problem for 2 weeks now so I don't think it is a replication problem in the sense that we need to give time for replication to happen.  I did verify today and it is still an ongoing problem.

**Comment by rhoesing** [comment]
Thank you for pointing this out to us.  We had an automated script that ran from midnight to 1p EST which we moved which should rectify this issue.

**Comment by DrSCarter** [comment]
Thank you for that feedback; however, the dates are still different from east/west coast.  I just checked and validated that this is the case.  Should we give it a day or two for replication or is this something that rectifies immediately?  Please advise.

Respectfully,

Dr. Stephanie Carter CISSP, CRISC, CISM, CISA, CCSK
PRINCIPAL | FEDRAMP ADVISORY SERVICES

COALFIRE | Coalfire.com<http://www.coalfire.com/> | (P) 571-350-8520 (C) 202-819-3734
1900 Campus Commons Drive | Suite 300 | Reston | Virginia 20164

**Comment by rhoesing** [comment]
Hi Stephanie,

I just updated the time the script runs today.  Would it be possible to do a quick call for you all the screenshare what you are seeing? Feel free to reach out to me ryan.hoesing@gsa.gov

**Comment by DrSCarter** [comment]
Yes.  If you want to join a zoom call right now while I have my team member that is on the west coast so that you can see what we are seeing, please let me know and I will send you the link asap.

Respectfully,

Dr. Stephanie Carter CISSP, CRISC, CISM, CISA, CCSK
PRINCIPAL | FEDRAMP ADVISORY SERVICES

COALFIRE | Coalfire.com<http://www.coalfire.com/> | (P) 571-350-8520 (C) 202-819-3734
1900 Campus Commons Drive | Suite 300 | Reston | Virginia 20164

**Comment by shivaalipour** [comment]
I was able to replicate the issue with other users. 
[Test](https://docs.google.com/spreadsheets/d/1GZCx8DViYa3GCUV-ZDcLZwHIjf8RyDyzhvIGrUmTcyg/edit?usp=sharing)

**Comment by DrSCarter** [comment]
We are still showing the same issue.  East coast is a day ahead of west coast.

Respectfully,

Dr. Stephanie Carter CISSP, CRISC, CISM, CISA, CCSK
PRINCIPAL | FEDRAMP ADVISORY SERVICES

COALFIRE | Coalfire.com<http://www.coalfire.com/> | (P) 571-350-8520 (C) 202-819-3734
1900 Campus Commons Drive | Suite 300 | Reston | Virginia 20164

**Comment by echovanderhyden** [comment]
@DrSCarter The cause was a little bit of everything.  The original source of this data was a date-only field.  Behind the scenes it wants to treat everything as a date/time timestamp so it appends a "midnight" time against our will.  This time inherits the timezone of the source document (eastern time).  When being displayed the browser uses the computer's timezone to interpret date objects.  Browsers think they're clever by seeing 5/1 midnight eastern and saying, "I need to subtract 3 hours because I'm pacific time and that moment in time is 9pm on 4/30."

I was able to reproduce the issue by manually changing my computer's timezone to Pacific.
