### ISSUE TITLE
Clarification on 'Authorized Service' field

### ISSUE THREAD

**Issue by moxleyaj** [GSA/marketplace-fedramp-gov#22]
On the FedRAMP Marketplace (product page), the information call out for 'Authorized Service' states that it represents "Total number of Authority to Operate (ATO) or Authority to Use (ATU) letters on file with the FedRAMP PMO. This includes the initial ATO and any direct reuse ATO/ATUs issued by a federal agency."

On the Google Form (for providing updated information for a particular service offering), the 'Authorized Service' field is asking for: "If your service offering has services included in your authorization boundary, please include them here. This may be more applicable to the Infrastructure-as-a-Service model vendors. Please separate by commas."

What data belongs in 'Authorized Service' field on the website?

**Comment by shivaalipour** [comment]
@moxleyaj  Thank you for bringing this to our attention. The information has been updated on the Marketplace site. 

For Authorized Services, the following data should be included: If there are microservices or applications included within this Cloud Service Offerings (CSO) authorization boundary, they should be listed within this section. This may be more applicable to the Infrastructure-as-a-Service model vendors.
