### ISSUE TITLE
"Service Model" is the only column heading that you are not able to sort by. Can we add it?

### ISSUE THREAD

**Issue by shivaalipour** [GSA/marketplace-fedramp-gov#34]

**Comment by echovanderhyden** [comment]
@shivaalipour i think we talked about this when we were developing this page.  

this data does not lend itself to be sortable.  do we have a suggestion on how this should be sorted?  Each row could have any combination of 1, 2, or 3 of the following always in alphabetical order:

IaaS
PaaS
SaaS

**Comment by shivaalipour** [comment]
Let's stay with alphabetical order.
IaaS
IaaS, PaaS
IaaS, SaaS
IaaS, PaaS, SaaS
PaaS
PaaS, SaaS
SaaS


Shiva Alipour

Contractor, FedRAMP PMO Support

FedRAMP <https://www.fedramp.gov/> | TTS
<https://www.gsa.gov/about-us/organization/federal-acquisition-service/technology-transformation-services>
| GSA <https://www.gsa.gov/>

m: 240.418.7699

e: ***@***.*** ***@***.***>

**Comment by shivaalipour** [comment]
8/24 changes pushed to main site
