### ISSUE TITLE
Updating CSV Export

### ISSUE THREAD

**Issue by rhoesing** [GSA/marketplace-fedramp-gov#47]
CSV Exports should display more information than just what is showing on the dashboard.  Depending on where you are pulling the CSV, different columns and rows should populate based on the requirements defined below.

Products:
- [ ] Add Authorization Type (Agency or JAB)

Agencies:
- [ ] Agency
- [ ] Cloud Service Provider
- [ ] Cloud Service Offering
- [ ] FedRAMP Package ID
- [ ] ATO Issuance Date
- [ ] ATO Expiration Date
- [ ] Business Categories
- [ ] Service Model

**Comment by shivaalipour** [comment]
Speak with Mike B. about what CISA needs

**Comment by shivaalipour** [comment]
From Mike B.:
 
Please see below:

- CSP Name
- CSP Offering Name
- FedRAMP Package ID
- Service Model
- Authorizing Agency
- Authorizing Sub-Agency
- Agency ATO Date 

This is what is required for CISA/Cyberscope. I know some of these are already there but this is the whole list

**Comment by shivaalipour** [comment]
From the agency: 
- ATO Expiration Date
- Business category

Look for old CSV

@rhoesing create example CSVs

**Comment by rhoesing** [comment]
@echovanderhyden I created 2 sheets with the requested output. 1) Products page CSV 2) Agency page CSV

Let me know if you have any questions.

**Comment by echovanderhyden** [comment]
this is working.  i need to confirm the source of the following data.  we may need to add this data the the json object created by the Google Sheets Script:

- Business Categories
- ATO Issuance Date
- ATO Expiration Date

**Comment by shivaalipour** [comment]
@echovanderhyden If it is helpful these are sources from the auth log

- Business Categories- **Master Authorization Status tab, column P (CSP Business Function)**
- ATO Issuance Date - (Need to confirm if this is the Agency ATO Date or Authorization Date)
- ATO Expiration Date- **Initial ATOs tab- column J (ATO Expiration)**

**Comment by shivaalipour** [comment]
first version release March 2024
