### ISSUE TITLE
Web pages have titles that describe topic or purpose.

### ISSUE THREAD

**Issue by shivaalipour** [GSA/marketplace-fedramp-gov#59]
Currently,  Same page title for all pages

Row 58

**Comment by echovanderhyden** [comment]
@michaelfrising i have a solution for this.

**Comment by shivaalipour** [comment]
CSO - remove the CSO name in light blue, leave the CSP logo
Agency- remove both the parent and sub.Move up design 
Assessor- Remove name in light blue, leave the logo

**Comment by echovanderhyden** [comment]
done. pushed to Sprint-2 branch

**Comment by shivaalipour** [comment]
issue resolved
