### ISSUE TITLE
Access to marketplace data (JSON or XML)

### ISSUE THREAD

**Issue by mike-wilson-wellhive** [GSA/marketplace-fedramp-gov#7]
As a cloud service provider, I appreciate having access to the data for the FedRAMP marketplace, in a machine readable format. This enables me to automatically detect changes to the marketplace, so that I can be informed about 3rd party FedRAMP authorized offerings that I could consider leveraging within my own FedRAMP authorized offering.  This also enables me to build my own index(es) of the data, to provide enhanced searching and visualization capabilities not afforded by the FedRAMP Marketplace website.

The currently-live version of the FedRAMP Marketplace website gets its data from a [JSON file publicly available in GitHub](https://github.com/18F/fedramp-data/blob/master/data/data.json). I have been able to meet my needs by using that JSON file.

The demo version of the FedRAMP Marketplace does not appear to fetch its data in a JSON format. It appears as though the data is all server-side rendered into HTML. This HTML content _could_ be crawled to achieve the same goal, but it would be nice if FedRAMP continued to make a JSON (or other, easily machine-readable) format available.

**Comment by shivaalipour** [comment]
@mike-wilson-wellhive Following up on Ryan's comment above? Do you need anything additional otherwise we will close out this issue. Please contact us if you need any further information.

**Comment by mike-wilson-wellhive** [comment]
That's exactly what I needed, thanks!
