### ISSUE TITLE
Trying to figure out if I am considered a Federal employee or a contractor so that I can complete package request that was authorized on 12/08/2023.<!-- Error while uploading Screenshot_20231212_141021_Chrome.jpg -->

### ISSUE THREAD

**Issue by Shai69bb** [GSA/marketplace-fedramp-gov#70]
Trying to figure out if I am considered a Federal employee or a contractor so that I can complete package request that was authorized on 12/08/2023.

_Originally posted by @Shai69bb in https://github.com/GSA/marketplace-fedramp-gov/issues/69#issuecomment-1852861037_

**Comment by shivaalipour** [comment]
Please reach out to info@fedramp.gov to help you further. 

thank you
