### ISSUE TITLE
VA page shows incorrect total of Authorized systems

### ISSUE THREAD

**Issue by va-user** [GSA/marketplace-fedramp-gov#71]
The FedRAMP marketplace page for Dept of Veterans Affairs shows 76 total Authorizations. However there are only 74 authorized systems listed. Either the total needs to be adjusted to 74 or the 2 missing systems need to be added. Can you please correct? I will reference this page often to know when I need to update my list, so having the correct total/systems will be very helpful. Thank you.

**Comment by rhoesing** [comment]
Hello,

The number is tallied using a formula, based on the number of ATOs we have on file.  This likely means the PMO either has two ATOs on file for two systems or 3 ATOs on file for one system.  We are working on an update to the marketplace hoping to release in the next month or so where you will be able to do a CSV export of all the ATOs which should be helpful to identify those ATOs.

Hope this helps!

**Comment by va-user** [comment]
Hi Ryan

Thank you so much for your prompt response. Will the export contain the Package names along with the Package IDs? That would be so helpful!!

Thanks,

Lisa Cheval
Business Process Analyst; Maveris LLC
Information Security Risk Management (ISRM)
Office of Information Security (OIS)
Department of Veterans Affairs (VA)
***@***.******@***.***>



From: Ryan H ***@***.***>
Sent: Friday, January 5, 2024 12:21 PM
To: GSA/marketplace-fedramp-gov ***@***.***>
Cc: Cheval, Lisa M. (maveris Llc) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [GSA/marketplace-fedramp-gov] VA page shows incorrect total of Authorized systems (Issue #71)


Hello,

The number is tallied using a formula, based on the number of ATOs we have on file. This likely means the PMO either has two ATOs on file for two systems or 3 ATOs on file for one system. We are working on an update to the marketplace hoping to release in the next month or so where you will be able to do a CSV export of all the ATOs which should be helpful to identify those ATOs.

Hope this helps!

-
