### ISSUE TITLE
Provider name should be text

### ISSUE THREAD

**Issue by rjadamson** [GSA/marketplace-fedramp-gov#8]
Minor usability suggestion.

The FedRAMP Marketplace page would be more user-friendly if the Provider field was text. Currently, Provider is an image of the provider's company logo. Perhaps separate Provider Logo and Provider Name into two discrete columns.

Some users will search for CSPs by name in their web browser's built-in search bar, instead of using the webpage UI's search bar. Right now, many of those searches will fail.

![Screenshot 2023-05-19 at 1 45 08 PM](https://github.com/GSA/marketplace-fedramp-gov/assets/134101501/46241714-9b5c-47fa-800b-430f2638700b)
![Screenshot 2023-05-19 at 1 45 40 PM](https://github.com/GSA/marketplace-fedramp-gov/assets/134101501/c5c7f2c8-03ab-4743-a396-66486b5810f6)

**Comment by rhoesing** [comment]
The PMO will not be implementing this change as users can search using the built in search bar.
