### ISSUE TITLE
Safari cache limit

### ISSUE THREAD

**Issue by shivaalipour** [GSA/marketplace-fedramp-gov#98]

**Comment by shivaalipour** [comment]
**Issue:** safari's storage limits are different than all other browsers.  the data became so big that safari wouldn't allow it.  Exceeds cache limits and the site will not function on mobile devices. 

**Solution:** The solution was to break up the json payload into different objects (products, agencies, assessors, etc) and divide them in between local storage and session storage.  

**Considerations for future:** This highlights one of the downfalls of json, it's very big because it precious space for field names.  If this happens again in the future, we can see if there is any unused data and try to reduce long field names.

**Comment by Yokymia32** [comment]
Nice work

**Comment by shivaalipour** [comment]
encountered same issue Cctober 2024
commit 586f6f78258fdd88d0dbd7525fe7542dd63a3fef

**Comment by david-waltermire** [comment]
Looks like PR #110 addressed this.
